### ISSUE TITLE
dev-14 Build and Pack

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/bering#15]
- [x] Beschreibung zur Erzeugung einer exe für windows in der alles benötigte enthalten ist.
- [x] Wo liegt die Datenbank, wenn das Programm in einer exe liegt? Legt die exe beim Start ein Verzeichnis an wo dann auch die Datenbank drin liegt?
- [x] Testen der Anwendung als exe
- [x] msvcp140.dll wieder hinzufügen

**Comment by chseip** [comment]
Im Prinzip kann man es einfach so machen:

    (npm install electron) # Falls global installiert
    npm install -g electron-packager
    electron-packager . bering --platform=win32 --arch=x64 --asar

Das `npm install electron` braucht man, weil ich Electron damals global installiert hatte und nicht direkt in der App.
`npm install -g electron-packager`: -g um es global zu installieren, sonst beansprucht es nur unnötig platz im package (node_modules ordner)

Edit: Dabei entstehen sehr viele Dateien, auf ownCloud sind nur die drin, die zum Start gebraucht werden.

**Comment by chseip** [comment]
Ich habe festgestellt, dass es besser ist, es ohne asar zu machen (wobei das auch Nachteile haben soll: https://github.com/electron-userland/electron-builder/issues/428), also:

    npm install electron
    electron-packager . bering --platform=win32 --arch=x64

**Comment by chseip** [comment]
1 Workflow zum erzeugen:

    npm install -g electron-packager # -g um es global zu installieren, sonst beansprucht es nur unnötig platz im package (node_modules ordner)
    electron-packager . bering --platform=win32 --arch=x64 --electron-version=2.0.0 --overwrite --icon=assets/icons/ico/1024x1024.ico # --overwrite überschreibt einen eventuel schon bestehenden build

für 32-Bit:

    electron-packager . bering --platform=win32 --arch=ia32 --electron-version=2.0.0 --overwrite --icon=assets/icons/ico/1024x1024.ico

oder für beide auf einmal:

    electron-packager . bering --platform=win32 --arch=all --electron-version=2.0.0 --overwrite --icon=assets/icons/ico/1024x1024.ico

Anschließend werden eine Menge Dateien erzeugt, von denen man nicht alle benötigt. Deshalb sind zu löschen:
- Ordner "locales"
- api*.dll
- blink_image_resources_200_percent.pak
- content_resources_200_percent.pak
- d3dcompiler_47.dll
- lib*.dll
- LICENSE*
- pdf_viewer_resources.pak
- ucrtbase.dll
- ui_resources_200_percent.pak
- version
- views_resources_200_percent.pak
- resources/app/node_module:
    - bootstrap-datetimepicker
    - dbf-parser
    - iconv-lite
    - readable-stream
    - read-dbf
    - read-pkg
    - read-pkg-up
    - shapefile

Die Exe liegt einfach im Hauptordner und öffnet im Prinzip nur eine Chromium Instanz, die auf dem Code in `\bin\resources\app\app` arbeitet.

2 Speicherort DB: `\bin\resources\app\app\db`

3 Testen:
- Liegt wohl an mir und hat nichts mit der Exe zu tun: ich kann keine Beringungen eintragen
- Menü (Nav-Bar) oben verschwindet: Problem zumindest konnt ich etwas weiter eingrenzen. Ich habe auch eine (hässliche) Übergangslösung gefunden:

Zeile 2 in views/nav-bar.html



    <span class="navbar-toggler-icon">Menü</span>



Änderungen in css/dashboard.css:

    body {
      padding-top: 230px;
    }
    .sidebar {
      position: fixed;
      top: 240px;
    <span class="navbar-toggler-icon">Menü</span>

Damit steht oben links "Menü" und man kann es ausklappen.

**Comment by chseip** [comment]
Sollte ja nun passen, gab zumindest keine negativen Rückmeldungen mehr.
