### ISSUE TITLE
dev-2

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/bering#2]
- [x] List of Beringungen
- [x] Filter list of Beringungen
- [x] Add classes to hide all nav-menues and function-menues at once
- [x] Speichern von Einzelformularen mit Beringungen
- [x] Form zum Suchen mit einer Ringnummer
- [x] Suchen nach Ringnummer und Anzeige eines neues leeren oder mit Wiederfunddaten gefüllten Forms.
- [x] Automatische Übernahme der user_id für beringernr
- [x] Automatische Übernahme von Datum und Zeit
- [x] Anpassung des Attribut zeit von datetime auf time
- [x] Anpassung der Werte in der Datenbank
- [ ] Abfrage und Befüllung der Arten Auswahlliste

**Comment by pkorduan** [comment]
Du musst unter 3rdparties awesomefont-4.7.0.zip auspacken.
Das Verzeichnis app/db habe ich in .gitignore ignoriert, denn das sollte nicht im repo stehen. Vielleicht müssen wir hier aber später noch mal trennen in ein Verzeichnis mit dem Schema zum Anlegen und Migrieren einer Datenbank und der Datenbank selbst. Dann sollten die Migrationen in das repo, die Datenbank selbst nicht.

Ich habe eine Login-Seite eingebaut. Du kannst ja mal sehen, wie die zum startup angezeigt wird.

Du kannst ja mal schauen wie man den controller.js geladen bekommt. Ich möchte dort alle Eventlistener registrieren, z.B. den von submit des Forms zum login. Aber später auch alle anderen on click. Ich denke, dass dafür eine eigenen Datei sinnvoll ist. Eigentlich wären mehrere Dateien unter einen Verzeichnis controller sinnvoll. Da könnte man dann pro modell beringung, wiederfund, nutzer etc. je eine Controller datei anlegen, wo die entsprechenden Eventhandler registriert werden und die Funktionen stehen, die dann die Aktionen ausführen.
Dito die views, da müsste man auch mehrere einstellen können pro Model.

Also die Struktur z.B. wie hier:

* controller
  * beringung
  * nutzer
  * wiederfund
* views
   * beringung
      * edit
      * list
      * table
  * nutzer
    * list
    * table
   * wiederfund
     * edit
     * list
     * table
* model
  * beringung
  * nutzer
   * wiederfund

Der Ordner views ist jetzt schon so etwas wie html

Ich habe versucht die Beringungen zu listen. Hab mich an tables orientiert. Hab aber noch keinen blassen wie das Resultset dann auf den view gemappt wird. Bestimmt muss man noch einen table definieren damit bootstrap den dann befüllen kann. Hab ich aber für tabels nicht gefunden.

Die Registrierungen von events also, z.b. on form.submit im Login view hätte ich gern in einer separaten Datei und dort dann registrieren mit 
$(#form_id).on('submit', function ...)

Die basic Funktionen sollten dann also sein.

Form für einen neuen Fund.
Form zum Suchen nach einem Wiederfund, wenn existiert anzeigen, wenn nicht leerer Fund. Was wann genau übernommen wird etc. kläre ich dann hier noch mal im Gespräch.

Am wichtigsten wäre glaube ich: Wie bekommt man persistent hin wer gerade eingeloggt ist. Schreiben wir das in die Datenbank oder halten wir das in einer lokalen Variable in JavaScript? Wohl letzteres. Aber wird ein solcher Status immer gehalten? Allgemein die Frage wie funktioniert das Session Handling bei electron?

**Comment by pkorduan** [comment]
Die Controller baue ich in dev-1 ein und merge das heute Abend in develop. Sag bescheid wenn Du weitermachen willst. Dieses Issue ist zu allgemein ich werde es noch kleiner und konkreter machen.

**Comment by chseip** [comment]
Ich hab heute weiter am parsen der dbfs und den autocomplete Feldern gearbeitet. Das Parsen klappt und ne Dropdown Liste mit den Vogelarten geht. Probleme:

- Encoding des DBFs
- Autocomplete Felder

**Comment by pkorduan** [comment]
Die Struktur ist noch nicht vollständig wie oben beschrieben umgesetzt, aber ansatzweise für controller, views und models. Der Umbau von weiteren Teilen des Codes in diese Struktur erfolgt dann wenn die jeweiligen Teile angefasst werden. Form zum Editieren ist umgesetzt, aber das Speichern noch nicht. Die verbleibenden Aufgaben sind oben als tasks angehängt.

**Comment by chseip** [comment]
Ich hab leider echt viel Zeit in vermeintliche Kleinigkeiten investieren müssen und bin trotzdem nicht zufriedenstellenden Ergebnissen gekommen. Hier eine kleine Zusammenfassung, vllt. hilft's dir ja weiter:

## dbf Parser
Hintergrund: Klar geht es, die DBFs erst in CSV zu transformieren und diese dann weiter zu verarbeiten. Aber es wäre schön, wenn man direkt die DBFs auslesen könnte, damit man bei neuen Versionen nichts mehr tun muss, außer die Dateien zu ersetzen. Aus den DBFs sollen Arrays gebildet werden, die dann für die `<option>`s in einrem `<select>`-Feld genutzt werden.

Ich habe folgende Pakete getestet:

- https://www.npmjs.com/package/node-dbf
- https://www.npmjs.com/package/dbf-parser
- https://www.npmjs.com/package/read-dbf
- https://www.npmjs.com/package/stream-dbf
Leider gehen sie entweder nicht oder sie sind async, d.h. wenn ich die Funktion zur Array-Bildung aufrufe, komt ein leeres Array zurück, weil im Hintergrund die DBF noch ausgelesen wird. Dann habe ich noch eins gefunden, das es sync macht und mit dem es funktioniert: https://www.npmjs.com/package/parsedbf

Funktion in der model.js:

    module.exports.parseDBF = function (fileName) {
        var arrayA = [];
        
        var dbfFile = fs.readFileSync(__dirname+'/data/'+fileName);
        
        var parsedDBF = parseDBF(dbfFile);
        
        for (var i = 0; i < parsedDBF.length; i++) {
            if (parsedDBF[i].ARNAME) {
                arrayA.push(parsedDBF[i].ARNAME);
            }
        }
        return arrayA;
    }

Einbindung parsedbf Paket in der renderer.js: `const parseDBF = require('parsedbf');`
Aufruf und Verarbeitung in der view.js: 

    let vogelArr = model.parseDBF("ARTEN.DBF");
    $('#vogelart').empty();
    $.each(vogelArr, function(i, p) {
        $('#vogelart').append($('<option></option>').val(p).html(p));
    });

Damit konnte ich nun mein Dropdown füllen, sah jedoch, dass deutsche Sonderzeichen Probleme machen:
![grafik](https://user-images.githubusercontent.com/3062968/35388964-2a8bbc44-01d6-11e8-9bee-a52c6132e6c6.png)

Dieses Problem habe ich leider auch nicht gelöst bekommen. Lösungsversuche habe ich mit folgenden Paketen erfolglos unternommen:

- iconv-lite (u. a. mit latin1, ISO8859-1, CP850, win1252)
- utf8.encode
- codepage
- ansi-to-json

## Autocomplete
Damit man die Vogelarten aus dem DBF dann nicht über ein Dropdown wählen muss, habe ich an einer Autocomplete/Combobox gearbeitet. Folgende Ansätze und Pakete habe ich probiert:

- jquery-autocomplete
- select2
- html5 datalist
- awesomplete
- suggestions
- node-autocomplete
- combobox

Entweder sie gehen gar nicht oder ich kann keine Optionen unterschieben (s.o. view.js). Dann habe ich festgestellt, dass es wohl nur auf der Formularseite nicht geht. Ich habe ein  jquery-autocomplete Feld einfach mal auf die nutzer.html geschmissen und siehe da, das geht:
![grafik](https://user-images.githubusercontent.com/3062968/35388855-bc7d2c38-01d5-11e8-9139-e5ad949c5b4e.png)

Die jquery.autocomplete.js und jquery.autocomplete.css habe ich erstma direkt ins app Verzeihnis gelegt und so eingebunden und genutzt:
renderer.js: `require(path.join(webRoot, 'jquery.autocomplete.js'))`

nutzer.html:

    <link type="text/css" rel="stylesheet" href="../jquery.autocomplete.css"/>
    <h2>Nutzer</h2>
    <div id="nutzer-list" class="container">
    </div>
    <div>
        <label for="jqautocomtestLabel">jqautocomtest</label>
        <input type="text" id="jqautocomtest">
    </div>
    <script>
        var states = [
          'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California','Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
        ];
        $(function() {
          $("#jqautocomtest").autocomplete({
            source:[states]
          }); 
        });
    </script>

Ich hab schon ewig rumprobiert und bin noch nicht dahinter gekommen, warum es auf einer Seite geht und auf der mit dem Formular, wo ich's brauche nicht. Es bleibt mir bisher leider ein Rätsel....

**Comment by chseip** [comment]
> Am wichtigsten wäre glaube ich: Wie bekommt man persistent hin wer gerade eingeloggt ist. Schreiben wir das in die Datenbank oder halten wir das in einer lokalen Variable in JavaScript? Wohl letzteres. Aber wird ein solcher Status immer gehalten? Allgemein die Frage wie funktioniert das Session Handling bei electron?

Wie gesagt, ich hatte das mit dem Login zunächst etwas anders verstanen gehabt. Aber ich hab mal kurz geschaut und ja, die (default) Session ist persistent: https://stackoverflow.com/questions/39129487/in-electron-is-the-default-session-persistent
Möchte man ein eigenes, persistentes Cookie setzen, mus man nur aufs Ablaufdatum achten.

Mehr zum Session Handling in Electron hier:
https://electronjs.org/docs/api/session

Und zu Cookies hier:
https://electronjs.org/docs/api/cookies

**Comment by chseip** [comment]
> Automatische Übernahme von Datum und Zeit

Das geht doch in meiner App schon. Habe dazu den bootstrap-datepicker verwendet (also zum selbst wählen) und die automatische Übernahme in der view.js so gelöst:

    var jetzt = new Date();
    $("#datum").val(jetzt.getDate()+"."+("0" + (jetzt.getMonth() + 1)).slice(-2)+"."+jetzt.getFullYear());
    $("#uhrzeit").val(jetzt.getHours());

**Comment by chseip** [comment]
> Autocomplete

Ich hab jetzt länger in die dev-2 reingeguckt und das mit dem Autocomplete bleibt mir ein Rätsel. In der Version geht's jezt nirgends, wobei man sogar n Balken nach unten bekommt, der auch kürzer wird, wenn man was eingibt. Es scheint also irgendwas zu passieren - es wird nur nicht richtig angezeigt. Kleine Randnotiz: Auf der Loginseite kommt nicht mal der Balken nach unten, was wieder die Frage aufwirft, inwieweit sich die einzelnen Seiten unterscheiden...

**Comment by pkorduan** [comment]
Christian, die Vorstellung der Anwendung wurde gut angenommen. Wir sind auf dem richtigen Weg.
Es funktioniert eigentlich schon das wichtigste. Jetzt sind noch verschiedene Kleinigkeiten zu machen, die wir dann in den nächsten Issues abarbeiten können. Ich habe hier eine Zweiseitige Liste was noch zu tun ist. Import z.B. wird nicht gebraucht. Tut mir leid, dass Du da jetzt Zeit investiert hast, aber es soll nur exportiert werden. Wie dazu bekomme ich in 2 Wochen eine Beschreibung.
Ich würde das hier erstmal schließen. Das Model, View, Controller Konzept ist jetzt soweit fertig und auch schon für beringungen, settings, users angewendet. So nach und nach können wir die anderen Sachen, die in app/view.js und app/model.js enthalten sind auf die Unterverzeichnisse verteilen und renderer anpassen.
