### ISSUE TITLE
npm install -> Cannot find module 'popper.js'

### ISSUE THREAD

**Issue by chseip** [pkorduan/bering#3]
npm install läuft soweit durch, die installiert boostrap Version ist aber wohl nicht ok. Beim Starten kommt `Cannot find module 'popper.js'`

**Comment by pkorduan** [comment]
Warum npm? Das Repo sollte alles beinhalten was electron . braucht.
Das ging aber nicht, weil node_modules Verzeichnis in .gitignored ausgelassen wurde. Ich habe das jetzt in dev-1 wieder reingebracht und nach develop gemerged.
Du musst also jetzt, wenn Du mit dev-2 weiterarbeiten willst folgendes Machen.
git clone https://github.com/pkorduan/bering.git
Damit wird das Verzeichnis bering an der Stelle angelegt.
git checkout develop
git checkout -b dev-2
Dann kopierst Du Dir Dein Verzeichnis db von Deinem alten Verzeichnis nach app und legst in bering ein Verzeichnis an 3rdparties und darin font-awesome-4.7.0 mit css/font-awesome.min.css. Kannst Du downloaden von der Awesome Seite.
Dann sollte electron . starten. Bei mir hat das geklappt.

Wenn Du weitere Issues anlegst, dann bitte mit einem Kürzel davor, z.B. dev-3. Später können wir dann so Entwicklungszeige besser filtern. Ich habe den Titel dieses Issue mal geändert.

**Comment by chseip** [comment]
Ok, ich hätte es vllt. ausführlicher formulieren sollen: Der einfachste Weg mit Node und Git zu arbeiten ist der, den du bereits angefangen hast. Du hast node_modules in die .gitignore gepackt. Möchte man nun am Projekt arbeiten, braucht man ja trotzdem die ganzen Dependencies, die liegen ja im node_modules Verzeichnis und werden in der package.json geführt. Das heißt nachdem man das Projekt in Git ausgecheckt hat, macht man erstmal `npm install`. Das liest dann die Dependencies aus der package.json aus und schmeißt alles ins node_modules Verzeichnis und dann kann man die Anwendung starten. Auf diese Weise muss man nichts hin und her kopieren. Das Problem jetzt liegt in der Version, die im Moment von Bootstrap installiert wird, mit der kommt oben genanter Fehler. Lösung ist recht einfach, man schreibt in der package.json fest. Ansonsten müsste man tiefer gucken, woran es liegt.

Dazu noch ein Hinweis: Installiert man mit npm ein Paket, z. B. read-dbf, macht man es so, damit es in die package.json augenommen wird:
`npm install read-dbf --save`
Das `--save` sorgt dafür, dass es in die package.json kommt.

**Comment by pkorduan** [comment]
Ok, Danke, können wir ja später noch mal anpassen, also lassen wir das Issue solange offen.

**Comment by pkorduan** [comment]
Die Sache ist für mich klar. Der Issue beendet. Wenn es noch Probleme bei Installation gibt package.json anpassen richtige npm Pakete installieren etc.
