### ISSUE TITLE
dev-3 Beringung edit Vogelartenliste und Datum, Zeitpicker

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/bering#4]
- [x] Abfrage und Befüllung der Arten Auswahlliste für den edit Beringungen view
Die Abfrage soll in einem extra Modell in einer Methode findWhere() erfolgen, wie auch z.B. im users model. Der Aufruf in dem beringungen controller function edit vor dem Darstellen des Forms. 
Die Optionen im Feld vogelart hinzufügen und das was im Datensatz ausgewählt ist auf selected setzen, falls vorhanden. Option ist attribut suchen, Value ist attribut arart.
- [ ] Datum und Uhrzeit in function setDatenAndTimeToForm so setzen, dass das mit dem Date und Time Picker funktioniert. Beachten, dass in der Datenbank das datum Feld jetzt den Typ Date und uhrzeit den Typ Time hat. Den Datentyp in der Datenbank auf Text ändern und den Tag so formatieren "DD.MM.YYYY" Im Model beringung in Funktion validate einen Switch Case 
 ['datum'].indexOf(field.id) > -1
einführen und darunter testen ob die Datumseingabe DD.MM.YYYY ist. Wenn der Date-Picker das Datum nicht als DD.MM.YYYY schreiben kann den Wert durch eine Funktion in das Format bringen.

**Comment by chseip** [comment]
Ich habe nochmal mit dem Autocomplete rumprobiert und durch diesen Ansatz/Workaround (https://github.com/electron/electron/issues/360#issuecomment-302041489) bin ich drauf gekommen, dass `datalist` doch tatsächlich funzt:
![image](https://user-images.githubusercontent.com/3062968/35694989-6a029d18-0783-11e8-832f-7ce0189d5add.png)
So sieht's in der edit.html aus:

    <div class="form-group row">
      <label class="col-sm-3 col-form-label" for="vogelart">Vogelart</label>
      <input type="text" id="vogelartInput" list="vogelart" class="col-sm-4 form-control" aria-describedby="vogelartHelpInline"/>
        <datalist id="vogelart">
          <option value="Spatz" />
          <option value="Geier" />
          <option value="Adler" />
          <option value="Meise" />
        </datalist>
      <div class="form-control-feedback" id="vogelartFB"></div>
      <small id="vogelartHelpInline" class="col-sm-4 align-top form-text text-muted">Vogelart.</small>
    </div>

Dieser Abstand zwischen Suchfeld und Auswahlliste sieht zwar noch etwas komisch aus, aber nunja...

Ich habe dann auch probiert, die Werte an die `datalist` zu übergeben. Ich glaube, ich habe die richtige Stelle gefunden (`module.exports.setValuesToForm` in beringungen.js). Aber irgendwie komm ich nicht richtig ans `datalist`. Jedenfalls sagt er mir `Uncaught TypeError: $(...).appendChild is not a function` wenn ich `.appendChild(option)` mache. Wenn ich in das Objekt (`$('form#beringung_edit_form :input[id=vogelart]')`) reingucke, sieht das auch echt komisch aus. Keine Ahnung...

**Comment by pkorduan** [comment]
Dann lassen wir den Datepicker erstmal außen vor. Das kann ja in einem weiteren Issue später noch mal aufgegriffen werden.

**Comment by chseip** [comment]
Der Datepicker funktionierte ursprünglich problemlos, nur das Autocomplete
macht wie oben gesagt Probleme.

Peter Korduan <notifications@github.com> schrieb am Di., 20. März 2018,
22:27:
